<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Charmonman|Dosis|Unlock" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@1,900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link rel="stylesheet" media="screen and (min-width:0px)"  href="css/movil.css">
    <link rel="stylesheet" media="screen and (min-width:650px)"  href="css/tablet.css">
    <link rel="stylesheet" media="screen and (min-width:900px)"  href="css/escritorio.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src = "js/app.js"></script>
    <title>ELECTROTODO</title>
    <link rel=""  href="">

</head>
<body>
   <header>
       <div id="header-top">
       </div>
       <div id="header-content">
           <div id="header-content-top">
               <div id="logo">
               <a id="inicio" href="#">
                   <img src="img/Electrotodo_Logo-04.png" alt="">
               </a>
               </div>
               <h1>ELECTROTODO </h1>
               <a href="#" id="navicon">
                   <i class="fas fa-bars"></i>
               </a>
           </div>
           <nav id="principal">
               <a id="cuenta" href="#">
                    <i class="fas fa-user-circle"></i>
                    <span>Mi cuenta</span>
                </a>
                <a id="Ordenadores" href="#">
                    <i class="fas fa-desktop"></i>
                     <span>Ordenadores</span>
                </a>
                <a id="moviles" href="#">
                    <i class="fas fa-mobile-alt"></i>
                    <span>moviles</span>
                </a>
                <a id="Audifonos" href="#">
                    <i class="fas fa-headphones-alt"></i>
                    <span>Audifonos</span>
                </a>
                <a id="contacto" href="#">
                    <i class="fas fa-address-card"></i>
                    <span>Contacto</span>
                </a>
                   
           </nav>
       </div>
   </header>
   <main>
       <div class="search">
    <div class="input-group mb-3" >
        <input type="text" class="form-control" placeholder="Tus Electronicos" aria-label="Recipient's username" aria-describedby="button-addon2">
        <button class="btn btn-outline-secondary" type="button" id="button-addon2"><i class="fas fa-search"></i></button>
      </div>
    </div>
    <header>
        <nav id="breadCrumb">
           <a href="#"><i class="fas fa-percentage"></i>Ofertas</a> <a href="#"><i class="fas fa-heart"></i>Favoritos</a><a href="#"><i class="fas fa-shopping-bag"></i>Pedidos</a>
        </nav>
    </header>
       <section>
        <div class="slideshow">
            <ul class="slider">
                <li>
                    <img src="img/maxresdefault.jpg" alt="">
                    
                </li>
                <li>
                    <img src="img/iphone-12.jpg" alt="">
                    
                </li>
                <li>
                    <img src="img/mt_series_wallpaper_1366x768_a.jpg" alt="">
                    
                </li>
                <li>
                    <img src="img/max.jpg" alt="">
                    
                </li>
            </ul>
    
            <ol class="pagination"></ol>
        
            <div class="left">
                <span class="fa fa-chevron-left"></span>
            </div>
    
            <div class="right">
                <span class="fa fa-chevron-right"></span>
            </div>
    
        </div>
        <nav>
        <article>
              <img src="img/laptop_hp.jpg" alt="">
              <div class="datos">
                <h2>HP 15-bs067ns N3060/8GB/1TB/15.6/W10</h2>
                <p>
                    Libre para cualquier operadora <br>
                    Wifi - Bluetooth - 3G/4G/5G <br>
                    Altavoces y micrófono <br>
                    Lector de SIM</p>
                  <div> <a href="">Comprar</a> </div>
              </div>
          </article>
          <article>
               <img src="img/pc_lenovo.jpg" alt="">
               <div class="datos">
                <h2>HP 15-bs067ns N3060/8GB/1TB/15.6/W10</h2>
                <p>
                  Procesador: N3060 (1.6GHz)<br>Familia procesador: Intel Celeron <br> RAM: 8 GB <br> Almacenamiento (HDD): 1 TB <br> gráfica: Integrada Pantalla: 15.6</p>
                  <div> <a href="">Comprar</a> </div>
               </div>
           </article>
           <article>
               <img src="img/samsung_galaxy.jpg" alt="">
               <div class="datos">
                <h2>Samsung Galaxy S7 Edge 32 GB</h2>
                <p>
                    Libre para cualquier operadora <br>
                    Wifi - Bluetooth - 3G/4G/5G <br>
                    Altavoces y micrófono <br>
                    Lector de SIM</p>
                  <div> <a href="">Comprar</a> </div>
               </div>
           </article>
           <article>
               <img src="img/laptop_toshiba.jpg" alt="">
            <div class="datos">
               <h2>HP 15-bs067ns N3060/8GB/1TB/15.6/W10</h2>
            <p>
              Procesador: N3060 (1.6GHz)<br>Familia procesador: Intel Celeron <br> RAM: 8 GB <br> Almacenamiento (HDD): 1 TB <br> gráfica: Integrada Pantalla: 15.6</p>
              <div> <a href="">Comprar</a> </div>
               </div>
           </article>
           <article>
               <img src="img/iphone.jpg" alt="">
               <div class="datos">
                <h2>iPhone 8 64 Gb Red</h2>
                <p>
                  Procesador: N3060 (1.6GHz)<br>Familia procesador: Intel Celeron <br> RAM: 8 GB <br> Almacenamiento (HDD): 1 TB <br> gráfica: Integrada Pantalla: 15.6</p>
                  <div> <a href="">Comprar</a> </div>
               </div>
           </article>
           <article>
               <img src="img/pc_hp.jpg" alt="">
               <div class="datos">
                <h2>HP 15-bs067ns N3060/8GB/1TB/15.6/W10</h2>
                <p>
                  Procesador: N3060 (1.6GHz)<br>Familia procesador: Intel Celeron <br> RAM: 8 GB <br> Almacenamiento (HDD): 1 TB <br> gráfica: Integrada Pantalla: 15.6</p>
                  <div> <a href="">Comprar</a> </div>
               </div>
           </article>
           <article>
            <img src="img/images.jpg" alt="">
            <div class="datos">
                <h2>HP 15-bs067ns N3060/8GB/1TB/15.6/W10</h2>
            <p>
              Procesador: N3060 (1.6GHz)<br>Familia procesador: Intel Celeron <br> RAM: 8 GB <br> Almacenamiento (HDD): 1 TB <br> gráfica: Integrada Pantalla: 15.6</p>
              <div> <a href="">Comprar</a> </div>
            </div>
        </article>
        </nav>
       </section>
   </main>
</body>
</html>